# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cb6b82d3b000a6ea4da741f8242abd896c9d625ec770e9337104366b45f9e08031b06d1aaf4cd2f57f730bbf9467ec8c602bba5356476b54e28b7e078ee09c7d

test:
  secret_key_base: 8a1f138a7d5821b3c96ec066bbd7a22fbb56acb47a9add6bc78b0f4295ce386eea67588673d9dedd53191a7bdc30b9f16b0852ccebe6a7aebdf2a3874427ab22

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
